name: Deploy JSDoc to StreamIt-docs

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Check Personal Access Token
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "Error: PERSONAL_ACCESS_TOKEN is not set."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install JSDoc
        run: npm install -g jsdoc

      - name: Generate JSDoc
        run: jsdoc -c jsdoc.json

      - name: Deploy to StreamIt-docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./docs
          external_repository: KucoDEV/StreamIt-docs
          publish_branch: main
          force_orphan: true
